from turtle import Turtle, Screen

kamtu = Turtle()
print (kamtu)
def kamutu_star():
    kamtu.shape("turtle")
    kamtu.color("red")
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)
    kamtu.forward(150)
    kamtu.right(150)

kamutu_star()
kamtu.left(150)
kamtu.forward(150)
kamutu_star()

my_screen = Screen()
print(my_screen.canvheight)
my_screen.exitonclick()